project:
  type: website
  output-dir: docs

website:
  title: "Justin Clark's Bioinformatics Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dge_overview.qmd
        text: DGE Overview

format:
  html:
    theme: cosmo
    toc: true
